apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/iam/api/v1/_authorize"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/iam/api/v1/login?originalRequestUri=$escaped_request_uri"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: monitoring
spec:
  rules:
    - http:
        paths:
        - path: /grafana(/|$)(.*)
          backend:
            serviceName: grafana 
            servicePort: 3000
---
