apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: monitoring
spec:
  rules:
    - host: grafana.raincove.io
      http:
        paths:
        - path: /
          backend:
            serviceName: grafana 
            servicePort: 3000
---
