apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authz
  name: authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authz
  template:
    metadata:
      labels:
        app: authz
      name: authz
    spec:
      containers:
      - image: erfangc/authz:latest
        imagePullPolicy: Always
        name: authz
        env:
        - name: URL
          valueFrom:
              configMapKeyRef:
                name: site
                key: url        
        - name: AUTHZ_DOMAIN
          value: raincove.auth0.com
        - name: AUTHZ_COOKIE_SECRET
          value: something-very-secret
        - name: AUTHZ_ROLE_CLAIM
          value: https://raincove.io/roles
        - name: AUTHZ_CALLBACK_URL
          value: $(URL)/authz/callback
        - name: AUTHZ_MONGODB_URL
          value: mongodb://mongo-authz-0.mongo-authz:27017
        - name: AUTHZ_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: authz-secret
              key: clientId
        - name: AUTHZ_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: authz-secret
              key: clientSecret
      restartPolicy: Always
