apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authz
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: authz/{{ .Values.environment }}
    repoURL: https://github.com/raincove-io/gitops.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
