apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: yahoo-finance-parser
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: erfangc/yahoo-finance-parser:latest
              # TODO make sure the SDK is pointing to the correct end point
              env:
                - name: CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: yahoo-finance-parser-secret
                      key: clientId
                - name: CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: yahoo-finance-parser-secret
                      key: clientSecret
          restartPolicy: OnFailure
