apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docs
  name: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
      name: docs
    spec:
      containers:
      - image: erfangc/docs:latest
        imagePullPolicy: IfNotPresent
        name: docs
      restartPolicy: Always
